### PR TITLE
Fixed version of "bootstrap-sass" in Gemfile

### PR DESCRIPTION
**Pull request by xaionaro**
Fix of https://github.com/raphendyr/gitlabhq/issues/7

### CODE REVIEW

**Comment by raphendyr** [comment]
upstream of `6.4` has `gem 'bootstrap-sass', '~> 2.3'` is that sufficient?

**Comment by raphendyr** [comment]
Any case, thank you for submitting issues for e and sorry for not noticing them before.

**Comment by xaionaro** [comment]
> upstream of 6.4 has gem 'bootstrap-sass', '~> 2.3' is that sufficient?

I don't think so :)

> Any case, thank you for submitting issues for e and sorry for not noticing them before.

No problem :)

**Comment by raphendyr** [comment]
I'll close this one. If problem exists in 6.4, please comment (and reopen if it's possible to you)

**Pull request closed without merging**
